### ISSUE TITLE
restart-in-place: test paths to node-local SSDs

### ISSUE THREAD

**Issue by adammoody** [ECP-VeloC/VELOC#15]
When we had problems with node-local SSDs failing, we added scripting to run tests against the SSDs on each node.  For that, the scripts have to know the path to the SSDs to be tested.  The library often knows this, so again this kind of info could be stored to a file.  In SCR, we had the scripts read the same config files as the library to identify the set of storage paths that were used.  For now, I've commented these tests out of the scripts.

**Comment by bnicolae** [comment]
This issue stayed inactive for a long time. Please reopen if still relevant.
