### ISSUE TITLE
SLURM restart-in-place script hangs when forcing prolog on down node

### ISSUE THREAD

**Issue by CamStan** [ECP-VeloC/VELOC#22]
If a node is in the allocation but is down (i.e., in `down_nodes`), this causes a hang when attempting to run on the down node.

https://github.com/ECP-VeloC/VELOC/blob/4144d924d9ae8d562ab2f187236a359a4eb0bab7/scripts/SLURM/veloc_srun.in#L57-L59

**Comment by bnicolae** [comment]
This issue stayed inactive for a long time. Please reopen if still relevant.
