### ISSUE TITLE
SLURM restart-in-place script double counts down node

### ISSUE THREAD

**Issue by CamStan** [ECP-VeloC/VELOC#23]
When testing [veloc_srun](https://github.com/ECP-VeloC/VELOC/blob/master/scripts/SLURM/veloc_srun.in#L57-L59 ) on SLURM, on back-to-back runs after a node was already taken down, the second run ended up double counting the same downed node in `down_nodes`.

Unfortunately I don't have the output from this test as it was done on a different machine.

**Comment by bnicolae** [comment]
This issue stayed inactive for a long time. Please reopen if still relevant.
