### ISSUE TITLE
VELOC install 64 bit libraries in /usr/lib instead of /usr/lib64

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ECP-VeloC/VELOC#25]
Too many hardcoded stuff, please let the user override the install paths with `CMAKE_INSTALL_LIBDIR`
https://github.com/ECP-VeloC/VELOC/blob/master/src/modules/CMakeLists.txt#L12
https://github.com/ECP-VeloC/VELOC/blob/master/src/lib/CMakeLists.txt#L13
https://github.com/ECP-VeloC/VELOC/blob/master/src/backend/CMakeLists.txt#L12

**Comment by bnicolae** [comment]
Thanks for the suggestion, fixed!
