### ISSUE TITLE
Change VELOC_MAX_NAME from size_t to a macro?

### ISSUE THREAD

**Issue by adammoody** [ECP-VeloC/VELOC#3]
With VELOC_MAX_NAME in veloc.h defined as a size_t variable rather than a #define, I'm getting the following error when trying to declare an array.

```shell
[100%] Building C object src/CMakeFiles/scr_o.dir/scr2veloc.c.o
/usr/workspace/wsb/moody20/projects/scr2veloc/src/scr2veloc.c:24:13: error: variably modified 'current_name' at file scope
 static char current_name[VELOC_MAX_NAME] = "";
             ^~~~~~~~~~~~
```

**Comment by bnicolae** [comment]
Switched from const to define. This should fix it for old compilers that do not support C99 (do they still exist in 2018?)
