### ISSUE TITLE
Fortran 90 bindingd to VeloC?

### ISSUE THREAD

**Issue by denisbertini** [ECP-VeloC/VELOC#30]
Is there already available Fortran bindings to VeloC ?

**Comment by bnicolae** [comment]
No, we do not support Fortran. We have an unmaintained experimental branch ("fortran") that offered such support in the past. You can check it out and try to merge it with the current master branch. If you are successful in making it work with the newer versions of VELOC, we'd be happy to add Fortran support into the master branch.

**Comment by denisbertini** [comment]
Well i would be interested in that since my program is written in Fortran 90
