### ISSUE TITLE
Alternative to OpenSSL for md5

### ISSUE THREAD

**Issue by chuckatkins** [ECP-VeloC/VELOC#32]
Currently you're using  the libcrypto from OpenSSL for MD5 hashing of files when computing checksums.  Since the only use of OpenSSL is for MD5, it's a pretty heavyweight dependency for just that.  Would you be open to a PR that brought in a different MD5 implementation in order to reduce the dependency footprint?

**Comment by bnicolae** [comment]
Chuck, sure in fact we don't even mind switching from MD5 to a different checksum as long as it works reasonably well to detect corruption of data.

**Comment by bnicolae** [comment]
@chuckatkins: since we did not receive a pull request in a long time, I am assuming this is not an issue any longer. Feel free to reopen it if needed.
