### ISSUE TITLE
Unable to run the example program

### ISSUE THREAD

**Issue by liaomin111** [ECP-VeloC/VELOC#37]
Hi, I am going to use VELOC in my project, but when I run the example program that comes with it after installing VELOC, there seems to be an error, I use **mpirun -np 3 heatdis_mem 2 heatdis.cfg** to execute the example program, here is the output log:

[INFO 0] [/home/Huimin97/soft/VELOC/src/common/config.cpp:68:config_t] using POSIX to interact with persistent storage in single file mode, path: /tmp/persistent
[INFO 0] [/home/Huimin97/soft/VELOC/src/common/config.cpp:68:config_t] using POSIX to interact with persistent storage in single file mode, path: /tmp/persistent
[INFO 0] [/home/Huimin97/soft/VELOC/src/common/config.cpp:68:config_t] using POSIX to interact with persistent storage in single file mode, path: /tmp/persistent
[INFO 0] [/home/Huimin97/soft/VELOC/src/modules/ec_module.cpp:15:ec_module_t] EC interval not specified, every checkpoint will be protected using EC
[INFO 0] [/home/Huimin97/soft/VELOC/src/modules/ec_module.cpp:21:ec_module_t] Running on a single host, EC deactivated
[INFO 0] [/home/Huimin97/soft/VELOC/src/modules/transfer_module.cpp:18:transfer_module_t] Persistence interval not specified, every checkpoint will be persisted
[INFO 0] [/home/Huimin97/soft/VELOC/src/modules/chksum_module.cpp:20:chksum_module_t] checksumming active: 1
mpirun: Forwarding signal 24 to job

The configuration file comes with the test folder, I just changed the mode to sync, and I don't know what's wrong, can you give me some advice?

**Comment by bnicolae** [comment]
Sure, what commands specifically generate this output?

**Comment by bnicolae** [comment]
This issue was inactive for a long time. Please reopen if still relevant.
