### ISSUE TITLE
example: function call within assert

### ISSUE THREAD

**Issue by psychocoderHPC** [ECP-VeloC/VELOC#38]
I checked your library and looked into your test case to get a feeling of how your library should be used.
The test is using the pattern `assert(VELOC_*())`, this is dangerous because in cases where the code will be compiled with `-DNDEBUG` the function call within assert will not be executed because `assert ()` is a noop.

example:
https://github.com/ECP-VeloC/VELOC/blob/4a8ec340ff562018130f89b61b38e4d1eb06d5f8/test/heatdis_fault.cpp#L123
https://github.com/ECP-VeloC/VELOC/blob/4a8ec340ff562018130f89b61b38e4d1eb06d5f8/test/heatdis_fault.cpp#L138

I know that the code I pointed to is the test case of VELOC but users will most likely start with copy-pasting from existing code and therefore propagate the issue into their own codebase.

**Comment by bnicolae** [comment]
Thanks for the feedback. Indeed, the intention was to make the example succinct, rather than a recommendation of how to use VELOC in production. We will fix this.

**Comment by bnicolae** [comment]
Done, updated examples are now available
