### ISSUE TITLE
VELOC_Route_file returns empty string during restart

### ISSUE THREAD

**Issue by adammoody** [ECP-VeloC/VELOC#5]
With the file-based method, during a restart, the app calls VELOC_Route_file to get the path to each of its checkpoints files.  However, veloc currently returns "" in this case, due to a check as to whether the library is in an active checkpoint state.

```
[ERROR 804727076878] [.../src/lib/client.cpp:145:route_file] must call checkpoint_begin() first
```

We need to also enable this to work during restart, i.e. for the following sequence,

```
VELOC_Init()
VELOC_Restart_test()
VELOC_Restart_begin()
VELOC_Route_file()
VELOC_Restart_end()
```

**Comment by bnicolae** [comment]
This is fixed in 57d39d0405daf04e16c31f4cb61ed214d87371d0
