### ISSUE TITLE
Include Fedora build instructions

### ISSUE THREAD

**Issue by tonyhutter** [ECP-VeloC/VELOC#6]
The quick start guide (https://veloc.readthedocs.io/en/latest/quick.html) should be updated with more detail on how to build VeloC, including listing all its dependencies.  Here's what worked for me on Fedora 28:

```
sudo yum install -y python3-pip cmake boost boost-devel openmpi-devel
pip3 install wget --user
pip3 install bs4 --user 
module load mpi

git clone -b 'veloc-1.1' --single-branch --depth 1 https://github.com/ECP-VeloC/veloc.git
cd veloc
mkdir build install
./auto-install.py --no-boost install
```

**Comment by bnicolae** [comment]
Tony, supercomputers do not allow you to install packages arbitrarily as root. That's why VeloC downloads and installs boost locally. These instructions need to cover both the case when you install locally and when you install on a supercomputer.

**Comment by tonyhutter** [comment]
Ok, that's fine if you don't want to include the full sudo line, but I think we should at least list the RPM dependencies.  I've referred back to this issue a couple of times when building VeloC on some Fedora VMs, since it has the RPMs I need to install before building.
